apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-go-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-go
  endpoints:
  - port: "8080"
    path: /metrics
    interval: 15s